 export const reactCourseData = [
    { id: 1, name: "Welcome Page", url: "https://docs.google.com/document/d/e/2PACX-1vRPv6W9HrZ_wPr4G0eW_QfvZm2rQkzO51XP0KSxKuuexkvVWVFw9IziW5ePRHWFvZI8Qsix4G5kOtaY/pub?embedded=true" },
    { id: 2, name: "HTML Introduction", url: "https://docs.google.com/document/d/e/2PACX-1vRGwueb60T4yEflUkjJoCOanXBjTXfPXKtgL4bdqJeHRRzwT6anwHP6V6ygD_wr55Lz4EMbC7ZNPnWm/pub?embedded=true" },
    { id: 3, name: "Elements", url: "https://docs.google.com/document/d/e/2PACX-1vSMrjBIGtJXrD0P-3Ex4P_pXbn8vPXuUlrBJPBZG_GyvGKWJPsP-OalUAdz35SdNIq6Qg84ng17LSed/pub?embedded=true" },
    { id: 4, name: "Block Elements Basics", url: "https://docs.google.com/document/d/e/2PACX-1vTaeyG8vnZQiwSFW9Ib_XcGztoAaV6Jb_1JxQzRk1DHqIaeCJ6yZIJmfSn2iAXOSvszu9zvrqZqaGoV/pub?embedded=true" },
    { id: 6, name: "Inline Elements", url: "https://docs.google.com/document/d/e/2PACX-1vTh8ONkkEN45eh1mITP0vffjQJBYRHLL-T3HfrULjs2SwiXH5kYVa01c3e_he7F-NCdIQQLKEfo0cln/pub?embedded=true" },
    { id: 7, name: "Void Elements", url: "https://docs.google.com/document/d/e/2PACX-1vT7ehYJOKD5H3QYJWEGArNtKRajfeWeGrum8JrKnp3dZ2lysbsJNxiiwK-f8pMGsUiOVmRy637kFl6X/pub?embedded=true" },
    { id: 8, name: "Semantic Elements", url: "https://docs.google.com/document/d/e/2PACX-1vRSECea6psRVlSK8RBs4lAfUVXLhx7MYCKSsBjZYCeHmPmEIjvPSCk4EhcJ_IU8BWrG4dhNl-19kn-0/pub?embedded=true" },
    { id: 9, name: "Non Semantic Elements", url: "https://docs.google.com/document/d/e/2PACX-1vQltLnjsGzxDFku625M-eXJPZPcaeaozaht1Hn4rLKnyhUJO1GUbHuca6J2K1uPZ1N9AxN939NkC5AR/pub?embedded=true" },
    { id: 10, name: "Element Attribute", url: "https://docs.google.com/document/d/e/2PACX-1vSNAO6TiwTui2y5LOpqXbAQfbhZgpipLu0ln-QWY_tgD-sMT40CsBJtWneAr24-UcyipW-IhrZcNLW9/pub?embedded=true" },
    { id: 11, name: "HTML Comments", url: "https://docs.google.com/document/d/e/2PACX-1vTm0jjXhj-aDGnb_qCB7-LhR33trEpwmAs_fMiMleKfdhH7I3ahztAukE8dZYJga1g9aoVGdCaGTanz/pub?embedded=true" },
    { id: 12, name: "Media Tags", url: "https://docs.google.com/document/d/e/2PACX-1vSmtaI5tLGThphnXmWYpXGO_ar8iDonbBcV8I9_lqYqTBR5Olj6DheLYYftCjBx6jgChVPT7sAJx9vL/pub?embedded=true" },
    { id: 13, name: "Table Tag", url: "https://docs.google.com/document/d/e/2PACX-1vRLlGSQdYmO3HTHIiPPG8Wu9gtx-8yzdpBcyIuUawLYD3O4rz5eGFlR-v_ocH5rRIhrx3OvQe8LsbBZ/pub?embedded=true" },
    { id: 14, name: "Form Tag", url: "https://docs.google.com/document/d/e/2PACX-1vSejZQCNmvUhn-_Q99AzFu_JrihWpjU_BPPFcDeWCWj9QqzRygcqEdyKQSKMMg8brxxKe2y2vDI21Re/pub?embedded=true" },
    { id: 15, name: "DOM Tree", url: "https://docs.google.com/document/d/e/2PACX-1vTixzB_Oc9mBXELdk7M85YNoak2pBsOTBmG4Q1vm0138wtuBQHBP3E5pAn28mi8LmsWyRhwtEeh8LKg/pub?embedded=true" },
    { id: 16, name: "HTML Entities", url: "https://docs.google.com/document/d/e/2PACX-1vQVyGowRraUPMpolpeisxeI8QLkJuXuCi1xDg4DLI8rIcGl1bAlQhqtzCt8NaNuOmtNPLU0nEv4hVsR/pub?embedded=true" },


    { id: 17, name: "INTRO TO CSS", url: "https://docs.google.com/document/d/e/2PACX-1vQMiW9dUYFvywESX7COiwWvcVeDl9gcbxtT9nzsFUo5_e1BOBgi_5gLKshIziwg1Qr4QIVV9UWT9xuj/pub?embedded=true" },
    { id: 18, name: "BASIC STYLES IN CSS", url: "https://docs.google.com/document/d/e/2PACX-1vRFwcDe3X2tLnwrm03UmkvtiFvSCasbayykh05IvXaLpOdxnXbFkqHaainAs8HcmD9NBI0RXfD5iLSD/pub?embedded=true" },
    { id: 19, name: "CSS UNITS", url: "https://docs.google.com/document/d/e/2PACX-1vTSDfUnqvmC0gsKuAXdsZtm6ebQHkYstZUsNYevwiWEmlO1wgxgP77DMRkuVanwTH_W19a0bY-xOBof/pub?embedded=true" },
    { id: 20, name: "INTERVIEW QUESTIONS- CSS", url: "https://docs.google.com/document/d/e/2PACX-1vQIjpxYPLU5Eo8xWzK-a9kpVuna1i6PpbIZerHTQcAf-KugiSrMD_tAa8Y9NE3h_CbljON9Ymbw6fMO/pub?embedded=true" },
    { id: 21, name: "BOX MODEL", url: "https://docs.google.com/document/d/e/2PACX-1vTjWkJCl5usDBLgOZE7XRiW3ELlMkBTE2ST6dlN4_Xopn63V8jEZJnDPzBN1Qo9RW9bVZD-_P2xxcK8/pub?embedded=true" },
    { id: 22, name: "INTERVIEW QUESTIONS - BOX MODEL", url: "https://docs.google.com/document/d/e/2PACX-1vRbsFQSr0TNbL9s_ntW7JFIjWH3rwfjkP3yVxHR99Yzp2VbwiB1Y9XKLasFhKkZe814iYBZjX4KEgsL/pub?embedded=true" },
    { id: 23, name: "CSS SELECTORS AND STYLING", url: "https://docs.google.com/document/d/e/2PACX-1vQEHtIN-5ZyOe61gFRz6VptBbGNSIZxqv3-fxZ-vzRd0CflOZQCzEsJATGlbvMfyAYzyVzWaTaaVBbU/pub?embedded=true" },
    { id: 24, name: "SIMPLE SELECTORS", url: "https://docs.google.com/document/d/e/2PACX-1vQUBIeA5Iymxxda1lrenZTidecHMpBA4ay8VgrU_jIQdhwPE0dBn381VmD3iiG8EoitLaX0rjIGVSKo/pub?embedded=true" },
    { id: 25, name: "COMBINATOR SELECTORS", url: "https://docs.google.com/document/d/e/2PACX-1vQwWqjJbyhqgfE3F1adySDMCkmnueHI29YDNgEttluOJ0kRMRPTgbySFRTWZEaCAxF4eD1gucVzQue8/pub?embedded=true" },
    { id: 26, name: "PSEUDO-CLASS SELECTORS", url: "https://docs.google.com/document/d/e/2PACX-1vSeh6hEFX_woSw4po2bCkDXTzVUJx1UZUQ5yPlZBL_f_eEXevSOoDyo3DZDtnLIgwAoRgeJDo3vRQrX/pub?embedded=true" },
    { id: 27, name: "PSEUDO-ELEMENT SELECTORS", url: "https://docs.google.com/document/d/e/2PACX-1vTaZhXddtb3rM_MJRGCq_0DJpyT2ITYEc7QuuHalCMfmnIVU02f3E5UzffkZag8l2KtdxoIqjJmd_EY/pub?embedded=true" },
    { id: 28, name: "ATTRIBUTE SELECTORS", url: "https://docs.google.com/document/d/e/2PACX-1vREK0lSJDVgxfb-sV_TvXd-gI0EgtGelHUJsHoxV6LHq1bwowu1BbjSzkZMJI3y5d7fXWf0m_z6ksAC/pub?embedded=true" },
    { id: 29, name: "INTERVIEW QUESTIONS- SELECTORS", url: "https://docs.google.com/document/d/e/2PACX-1vSRdlIymCThUCZVv8t5BgdZBl2UKE8CRvCnLlp-nl11G4JTwoTsjUcibvug_0YH7pinHNVCa51Gj3A9/pub?embedded=true" },
    { id: 30, name: "CSS LAYOUTS", url: "https://docs.google.com/document/d/e/2PACX-1vSrJQCf7WBXMy7NMJX1iYOl99o6qkSoWgKrqzVsv6Z61GeXYDXIajxPa9RKAuyA4yGEKrFyHLtHHkW8/pub?embedded=true" },
    { id: 31, name: "Flexbox", url: "https://docs.google.com/document/d/e/2PACX-1vTYEOPoo7ga1ixI2IfqxdoG1JdUsAqjFw4WH6iHFy5vwZ6Ie8I3zfnkgUFYFpHhz2MkiJL550DrAH0I/pub?embedded=true" },
    { id: 32, name: "CSS FLOAT", url: "https://docs.google.com/document/d/e/2PACX-1vRYhxVHD_SB2n5_TCRCs4O4VkULOZGcodEyy8N3L47_h5nj2h4Ah3Y0j5GBBbBfqpzkLEhwUuI6R3Yh/pub?embedded=true" },
    { id: 33, name: "CSS POSITION", url: "https://docs.google.com/document/d/e/2PACX-1vQ26HK0PpOMCOK90XjT9n4ME06ImqJFffjKqLpa90nf4iI-uhazobwMhiBhPBBW-Zgn1V_oTKX15qM2/pub?embedded=true" },
    { id: 34, name: "POSITION: STATIC", url: "https://docs.google.com/document/d/e/2PACX-1vT7soXQmAceUapGCm6CayAOrEXl5vXpHA5PAGDncVP7eIKCN11jkW8T39PSitYxvIEo_a6SABKmSK7W/pub?embedded=true" },
    { id: 35, name: "POSITION:RELATIVE", url: "https://docs.google.com/document/d/e/2PACX-1vRB6dOx9MUVeHKkfvQMLIX-tmCIIL0wSj3f2W10j8jjQ_dxuLeI4Axt0SRUnF279Zge27ARgZplK1i6/pub?embedded=true" },
    { id: 36, name: "POSITION:ABSOLUTE", url: "https://docs.google.com/document/d/e/2PACX-1vSrfwtgovdvxdwE8nUdMmlYdiZAMy0-TyJPBH7cjjiKtFT3mwNH5e8_q2lmHJxuIu1uichXLELnbDHK/pub?embedded=true" },
    { id: 37, name: "POSITION:FIXED", url: "https://docs.google.com/document/d/e/2PACX-1vTS7pCSBA9qV6eiz6Oq9glhSvFAEaI2789Xrq21zkxR532Evn10PjOAcpaIiUo4Gc8mzxZO5h5yNYzu/pub?embedded=true" },
    { id: 38, name: "POSITION:STICKY", url: "https://docs.google.com/document/d/e/2PACX-1vTZHvTYZ_srf-RfDWNYW65T9PsxjzBc8uIK6QDLb5cNzRiaZLmq3RkLQZ8rgbJwPdR18mMjZeCqd-Rm/pub?embedded=true" },
    { id: 39, name: "INTERVIEW QUESTIONS - LAYOUTS", url: "https://docs.google.com/document/d/e/2PACX-1vReK0hhCjqUsj81kh6iqxJG2PCiemkl9BSE_HOS5x6aMn5-xk3hBOLL34EeT-ngzeZczTaqrJULQbTQ/pub?embedded=true" },
    { id: 40, name: "Clean Code in HTML & CSS", url: "https://docs.google.com/document/d/e/2PACX-1vTuqi51MxBiyCvuBTlAIU47OXUF7rFxQUYGBc4-xDefASOrHL9R-MZKkUB6EWA5oMpefO8EJ0y_PT9S/pub?embedded=true" },
    { id: 41, name: "ACCESSING EXTERNAL LIBRARIES", url: "https://docs.google.com/document/d/e/2PACX-1vR5S4h3Q4c-CbNhmh9B7RpNdgGASf0yfb1VvRelUMpMFp1Upq7XTnB7vt4zM766mZ7V3nIehwBQdQDg/pub?embedded=true" },
    { id: 42, name: "CSS GRID", url: "https://docs.google.com/document/d/e/2PACX-1vSuPl5cvHTC3Vs--nGwa6fVEorm6iS8bvSH1yLuWTYVL21u9IBXEdcQZRQiGtt-vTPLFUHvBbD--eVW/pub?embedded=true" },
    { id: 43, name: "RESPONSIVE DESIGN", url: "https://docs.google.com/document/d/e/2PACX-1vQKnTSNKEkDW8II5IbTuNdqedYZJip66c8z9RpmXpioloffLYa65fVQz_YSzfxtDWmFQ7YdXW5uPFbP/pub?embedded=true" },
    { id: 44, name: "INTERVIEW QUESTIONS -Responsive", url: "https://docs.google.com/document/d/e/2PACX-1vRDbR0XIBjCzX7qCCRPHyFNdl0X2l8DCd4GWR1z9j6LeWrK2pOm2gL5mtCjo9DafXrFgQDwQQKi8aJ_/pub?embedded=true" },
    { id: 45, name: "CSS Animation", url: "https://docs.google.com/document/d/e/2PACX-1vQu80pCKt1ku4c7BXXYHs8R-X1PxfEVDyeMeiZQ7Q1x8rzC02zbs318Sf4cqQgp7bd9F3alXWkE_Ul6/pub?embedded=true" },


    { id: 46, name: "INTRODUCTION TO JAVASCRIPT ", url: "https://docs.google.com/document/d/e/2PACX-1vRYf5ISNb1_aloCRVh3F9T3DjXZQWGN-Kh4tpLp_thMcUPHt-kZ_gzsni9_yvY2YEazvyvy9Tm6dD8d/pub?embedded=true" },
    { id: 47, name: "JS Output Methods", url: "https://docs.google.com/document/d/e/2PACX-1vSKp9tM_ep0sG1cTsMlkT7t4o99AzpjfJN6hhvFGbDiSEh54BD6xFKlc1G5wiDQMVSJZvZ_VYD_6Rjk/pub?embedded=true" },
    { id: 48, name: "Variables in JavaScript", url: "https://docs.google.com/document/d/e/2PACX-1vRv7sQLuSLd9t8i0qXK2yvmCC3ycsWmL8Dkqs4NLGXyuFJ5TwjYG10bIr1t_eM25GtumrpIN2aEWsJJ/pub?embedded=true" },
    { id: 49, name: "JavaScript Datatypes", url: "https://docs.google.com/document/d/e/2PACX-1vQDH7M7XKTuFwEywbf45l6uoGntYPLBRx_VLB5zcZOrh-vqvLI3yzh3xVOs9tfSVNlxPEPChv9SEqm2/pub?embedded=true" },
    { id: 50, name: "Regular Expressions", url: "https://docs.google.com/document/d/e/2PACX-1vQr4mr4VNA0ZPKMaanZiz6EX6x9Gz9rUcPb7bahP0k0nND5zk8O-v8dLfFJqXfOePgQx-jdR1kguysC/pub?embedded=true" },
    { id: 51, name: "Strings in JavaScript", url: "https://docs.google.com/document/d/e/2PACX-1vQfPKvPGhiFM-5vYNXCcWCAf1fD6aYSzoaQe92wy-1588shkF0STqoYK-bl9sP-p_WB1KbghXhJysVE/pub?embedded=true" },
    { id: 52, name: "JavaScript Arrays", url: "https://docs.google.com/document/d/e/2PACX-1vQSPxWXmJb-MUlLf-XQSTlSTy2XnMR2iz0-NB5T7KZuZzpURRkCkhKHuNcsHVSIc4kObcXtHRkZMuPF/pub?embedded=true" },
    { id: 53, name: "OPERATORS IN JAVASCRIPT", url: "https://docs.google.com/document/d/e/2PACX-1vRt1tnvufqljfEDLgmTFSiBDuX_KHs4m5SRR1m1sKSBIjqUyfQ4tDOomwd65zr1R70ULnAiDKFOhMtL/pub?embedded=true" },
    { id: 54, name: "FUNCTIONS IN JAVASCRIPT", url: "https://docs.google.com/document/d/e/2PACX-1vS71Ozt2r3RFdOJ_rwu1aohWOQ4RTCsYXNbr4Qu5L7fbuwM75HnZXbhVbnM2c75OIbCaN3MaL1ru8mx/pub?embedded=true" },
    { id: 55, name: "CONDITIONAL STATEMENTS", url: "https://docs.google.com/document/d/e/2PACX-1vRnm_s43BfFeHAW2hSMxJKYJqit8TeqCJjNpy923jeorfEWDuOXJJhgujSBFkPNqnUGzUvFTSvBih6A/pub?embedded=true" },
    { id: 56, name: "LOOPS IN JAVASCRIPT", url: "https://docs.google.com/document/d/e/2PACX-1vS7gr5cmQZhh4quskQR-fRYvmU3IOosnNBOxfdo0qxPb_q6gQE1KZJZZRBpZaDnd7wAlebXDnrzuDdc/pub?embedded=true" },
    { id: 57, name: "BREAK & CONTINUE", url: "https://docs.google.com/document/d/e/2PACX-1vQ_EbEDomJiYAKUeFfU0t-THja-ZUkBOBRd7M9Mw4oeNfrFN22YRPf_J4-QoCT-f2hqt10VoUx-XQY9/pub?embedded=true" },
    { id: 58, name: "CLEAN CODE IN JAVASCRIPT", url: "https://docs.google.com/document/d/e/2PACX-1vRrq5HgPvnTGDj913fnhGKahIlLA5rZbfOQpXGe-pcnDTMM_oCeP-J0GXmmV5RedmjZ6nVvmYdShMe9/pub?embedded=true" },
    { id: 59, name: "Debugger in JavaScript", url: "https://docs.google.com/document/d/e/2PACX-1vQhbsincpyvNHL6AvAsnHjrw-qgrVoK0zrL2zdgmbBMIwoYnlnmvc0R9BUB_ddmqUItbPgBmy-sEEj5/pub?embedded=true" },
    { id: 60, name: "PLACEMENT OF SCRIPT IN JAVASCRIPT", url: "https://docs.google.com/document/d/e/2PACX-1vR6_lzMVGTeZDv61dYR-ut9B4xkHW3WpQeqArulu2z36uhVYdEJz0ScObEKVigXsh94hig8bVDgc-7G/pub?embedded=true" },
    { id: 61, name: "DOM — Document Object Model", url: "https://docs.google.com/document/d/e/2PACX-1vSx87tlU1lvtIuHKa4RNPRoqmvRV9Z7Si_hGyZ-C6_dbl_rk0d6nho9Gg8DKvZh2x-qKphiGdet_r2C/pub?embedded=true" },
    { id: 62, name: "JavaScript Events", url: "https://docs.google.com/document/d/e/2PACX-1vRsQuHr15h_asIGPLsdeuDU9UOXr8yx1-9PJQubaXHsx1udDcVWoO8MaQju5SqciLGbkYq4w1f_JQ4g/pub?embedded=true" },
    { id: 63, name: "DOM MANIPULATION", url: "https://docs.google.com/document/d/e/2PACX-1vQvOge_m5R-0hatSP78Y8KEjrm75CZHFgDowjMCPWvX25Qpm0cJmknEfWIurlcDIsTkOJDfD8X65t08/pub?embedded=true" },
    { id: 64, name: "Inbuilt Methods", url: "https://docs.google.com/document/d/e/2PACX-1vQ4rA3jlxe87dJx5QiX9tc0LsNH4f4O-NVSBcTTgzr4pSwaW_jTWl0170c3Bt9sSJm5Gjqmx1eERxXi/pub?embedded=true" },
    { id: 65, name: "HIGHER ORDER METHODS", url: "https://docs.google.com/document/d/e/2PACX-1vRP95SQUQZx845ebbEee1CGSpDaRrchIm4tZNELOmniHm3MxclPbMFcfCFPftldOAizMkNAOw9RUPwd/pub?embedded=true" },
    { id: 66, name: "Math Methods and Number Methods", url: "https://docs.google.com/document/d/e/2PACX-1vSYx0Z4MRAp9lB6w7FSz9pBaWtX3DMIrfMhIxBC5STBaypL1TNjIEBfdyTXm7flNX4dtUJeB-H8k56r/pub?embedded=true" },
    { id: 67, name: "JavaScript Timers", url: "https://docs.google.com/document/d/e/2PACX-1vQzs85VBL09gQKFD-hdY-pQshCjkqowwN_htEIenipxBnJpdZiZHXlNqeuebwDoLxnKX3_ZCwKQRZkS/pub?embedded=true" },
    { id: 68, name: "JavaScript Date Methods", url: "https://docs.google.com/document/d/e/2PACX-1vRFOpthwSeN4bVnJff1TphEgyuBmRA4wvgRvyDyoVCcXzZth7cNmwVOHHrNv5JOb-nK-wQCEcKkA8WC/pub?embedded=true" },
    { id: 69, name: "JSON", url: "https://docs.google.com/document/d/e/2PACX-1vSJ0v6HTdlcP-87aS6H1wE9idUDkiUtiCZkArBpGmYSp6jJYDW_2EvS_WctYSI8FFF4BiAeHOIWNJAe/pub?embedded=true" },
    { id: 70, name: "Spread vs Rest Operators", url: "https://docs.google.com/document/d/e/2PACX-1vQzGUBNrI2C3rE3XDVB5RHK_CqOyWfHA4PWhJ6xlGQ8h-nrU4bssez0eEANoC_nR_Mk6moKRgr2hAwn/pub?embedded=true" },
    { id: 71, name: "JavaScript Destructuring", url: "https://docs.google.com/document/d/e/2PACX-1vRBYRbwS1DGFj9zVSmutCoQxDd_MbwrnGZO6Nc2lWcXrpldJS-S7frOJrnjs3-5DtUyjF_S9wnGqiIA/pub?embedded=true" },
    { id: 72, name: "Shallow Copy vs Deep Copy", url: "https://docs.google.com/document/d/e/2PACX-1vQkZReSc4SU2FiCq5XY297YfkZp2e1pC-zouFs34tKQCkKjUSqlvEFBcV_woy6OWDsL_2AdwyzyIc3k/pub?embedded=true" },
    { id: 73, name: "JavaScript Storage", url: "https://docs.google.com/document/d/e/2PACX-1vSM789o3xaTvrSSAXSCp0DNB8KcmOHyoJt1XIb7Z8aDr-lbfp8hwxeKhP-TnVEYAo-nb-ACoKOX2X-B/pub?embedded=true" },
    { id: 74, name: "Asynchronous JavaScript", url: "https://docs.google.com/document/d/e/2PACX-1vQzhAqPi6oMW0oc8C64mOwvOZCkjXdlqKc9HJNA5h6YhmxrD1c_ztk9yFkRf9QhRud5x2dFbLkRQa60/pub?embedded=true" },
    { id: 75, name: "Callback Function in JavaScript", url: "https://docs.google.com/document/d/e/2PACX-1vRTYa8Q4Nk2IieG2wpDs12GY1iG3zt_uqKH2XHKR_wh1bRobwajmGp2R4XStSJw_PXeRZp2be-3_PGO/pub?embedded=true" },
    { id: 76, name: "JavaScript Promises", url: "https://docs.google.com/document/d/e/2PACX-1vSHwrNVhiKrr3Dwj0W_2jaozht2AEVTmWCG_R16Kju8tpWBM4In9Of_xi64V82bZcfHLg2thxQQq_oZ/pub?embedded=true" },
    { id: 77, name: "Async and Await", url: "https://docs.google.com/document/d/e/2PACX-1vQxFowkMxh_9la1QjBMQrK804J4O2Pi3JshcwIGeDjVHkbYeu-MQ17U3WWjPMWHGKwh35UY7M2ynqoD/pub?embedded=true" },
    { id: 78, name: "Event Loop JavaScript", url: "https://docs.google.com/document/d/e/2PACX-1vRsnXBJH8YwfvzjJJ3FcqDFpcoRLnMHszpLUk5eMrVMeNX8CXFjvL8ur1qxbDt5c2LcKOPIMUbwrg5Z/pub?embedded=true" },
    { id: 79, name: "API", url: "https://docs.google.com/document/d/e/2PACX-1vT2uKZBeHdjWs59xwvcceLbXgM-G-nu8kIjmI93HC-KzyU9HoDyz_GeYSG_bo_SBm8Palzk8_vRcKd0/pub?embedded=true" },
    { id: 80, name: "JavaScript Closures", url: "https://docs.google.com/document/d/e/2PACX-1vT4iwFooPirCNbMKCBW4fcfKicLzS1r5frFaL0257sg26volsM24nfUJQKtqXcDt1zr9_nUZKa4Jj-P/pub?embedded=true" },
    { id: 81, name: "PreventDefault", url: "https://docs.google.com/document/d/e/2PACX-1vSpaCCni6gOlgnj5ogMqA8mT5fAbmGsJfyFoVhgT4ZQI8vKsTAdwSNFef7MeG7UmBmB-Tun2Iz4qQHx/pub?embedded=true" },

    { id: 82, name: "Introduction to React", url: "https://docs.google.com/document/d/e/2PACX-1vT1qR_Kx-AkOvRoZuTz10GJY8FGi_UiXJA3s2Nvk3oSIoe7src31H7GW-VC7k849kSD5si0pMcPXRbd/pub?embedded=true" },
    { id: 83, name: "Project Setup For React", url: "https://docs.google.com/document/d/e/2PACX-1vSQGxahj9Zz0Y0fGDWMJfORnV6zJm2ebWQ34gfghYWKcw_LZ92GwggRT0BhxrdiRzLSLBxfhbDtHPOY/pub?embedded=true" },
    { id: 84, name: "HOW REACT APP WORKS", url: "https://docs.google.com/document/d/e/2PACX-1vRBNuIZtwJr5LMt0U-TSs3QXA0sjvugPhTfqaA2VUIPuI1Bn0CF0JxtgLsQ1BSMVSWLmOFoLvnJFy0W/pub?embedded=true" },
    { id: 85, name: "React Folder Structure", url: "https://docs.google.com/document/d/e/2PACX-1vS63XUIuW_IpJqOKQ15g0vrevYe_FJd-AtRKVnNH3O2Ow37PfXqPgu89EcmUGLAXSEGzHpLr1IVX5Ki/pub?embedded=true" },
    { id: 86, name: "Render HTML in React", url: "https://docs.google.com/document/d/e/2PACX-1vSWjVz05ZkqqOscHHy9m8Hxj-sRLx7-KhfyFEcfFXatGWRdPLxyBgqUwQCxarNGqMvnW6jHX-xCp1j-/pub?embedded=true" },
    { id: 87, name: "JSX In React", url: "https://docs.google.com/document/d/e/2PACX-1vQXPuLhBvnzVOsFFrRC3Z3aFFUzifg_LAXVEl5A9xIbiv4US9tomWdMwVIZOK-4Vj4wGZPSD8c9Niot/pub?embedded=true" },
    { id: 88, name: "Components In React", url: "https://docs.google.com/document/d/e/2PACX-1vQ24DTBSYT988c-YyA5O-k9JQuisjuDxgGGrtxfMO0l1qSMFoEqfteBftPC9O5wGoiw41NTNSCOjHNs/pub?embedded=true" },
    { id: 89, name: "Props in React", url: "https://docs.google.com/document/d/e/2PACX-1vREmuznrtyET9QcHbCcWWje0n00Fey7Q7P0m5IqPQQ1upQBhjfkKd7APcGwov5nWvmYW0JakeD-3kX5/pub?embedded=true" },
    { id: 90, name: "useState In React", url: "https://docs.google.com/document/d/e/2PACX-1vR8C1CHUt0AbyWEIRH9jxhPWMaUiFegrRIpt9bK59JL6hh_ZSMe8a1kukWTlWMRzNVld68DUVnG6lby/pub?embedded=true" },
    { id: 91, name: "Component Lifecycle", url: "https://docs.google.com/document/d/e/2PACX-1vSWPgNEsgy0ZSX3TBkaZF0X_Jkpr9O1tzvoKZxxP9_ZhzQM85aMbBTYDprkjnu1ytn1grrV5o1AX6Y9/pub?embedded=true" },
    { id: 92, name: "useEffect in React", url: "https://docs.google.com/document/d/e/2PACX-1vQY0csD-E-xxQ_D_z8iO4zAeBgttPQgu7CZ8sU8MQxMVPsr7oNmZzcxwMXY955ZaJXL-Ls4tsbG2nSC/pub?embedded=true" },
    { id: 93, name: "Reusable Components", url: "https://docs.google.com/document/d/e/2PACX-1vSNTt1sKiIWzEeGAbCa1cZ90Pij_YLXJPX5_zUHsOfgqJN8T92KZLi4NFE-a7QOVW_y3vFVjxVahYQN/pub?embedded=true" },
    { id: 94, name: "Material UI", url: "https://docs.google.com/document/d/e/2PACX-1vTnTasvZiwIgHINbhT6UWQtFTw7P4IzCXbzKzFsrIMlbAt3HDiBYrxHozHN89wW8oTFJ_9T5twFzAHd/pub?embedded=true" },
    { id: 95, name: "MUI Components in React", url: "https://docs.google.com/document/d/e/2PACX-1vQhABMVDLlNb25xtYr8-dwAIA4pVlgrYg-XC4FEH9L05DWZDGpmR4-Zhv3rTpH5H1gmv1KuJnASOuwr/pub?embedded=true" },
    { id: 96, name: "Material Icons", url: "https://docs.google.com/document/d/e/2PACX-1vTfCTGfoaqN8vCwCfDs7PZ0Sk8RrjJmA3elE-kS78pNaE3Osxp2reaxyIQtvm20vlqd31v3Yf4KeqZe/pub?embedded=true" },
    { id: 97, name: "MUI Modal", url: "https://docs.google.com/document/d/e/2PACX-1vQAgMcXrqGMD7WS188-PHvyr-ZW8hfuxYJNI7nFBCgjWdAqQ8VlDflo4uNt8m_i1ppq37a5gsiSZFWe/pub?embedded=true" },
    { id: 98, name: "MUI Grid", url: "https://docs.google.com/document/d/e/2PACX-1vQXKuzz4WeY8lPr_O_VUA3gWV7e7eQ5s6sX4x79bgh1vfQioE647U4fHB0zJZhprgDwhmtTGytducHP/pub?embedded=true" },
    { id: 99, name: "Styled Components in MUI", url: "https://docs.google.com/document/d/e/2PACX-1vTE8fRryXnhFJ48xVwo1TL6-QH70O67dLOT5-jy0qRWjEJVGK49gabFqW1nMxiXwHOnWukFoUsjIiAr/pub?embedded=true" },
    { id: 100, name: "React Router", url: "https://docs.google.com/document/d/e/2PACX-1vSFS5z63gMVlhyQttOJJTJl10AVFI69Bz53xpSHZIIICUS2UcHP3GGOCDSDa6h7Nz7Qy8-calurH_YB/pub?embedded=true" },
    { id: 101, name: "No Match Route", url: "https://docs.google.com/document/d/e/2PACX-1vTr0j1pnq2ZUBYZALFJZ2FRgDeJ7acKsFhTiv6eh__M-cu1ZRFf95GxGIaXj2Z0z1GPBU3fA591aK-M/pub?embedded=true" },
    { id: 102, name: "Dynamic Routing in React", url: "https://docs.google.com/document/d/e/2PACX-1vRfvxHuaT0-7k-tpC36jHE9w2REv56lF1bBuwnzzZN8xJouaXgXsdiKZrr2NG5uOFn95b4MSHUwDU6a/pub?embedded=true" },
    { id: 103, name: "Nested Routes", url: "https://docs.google.com/document/d/e/2PACX-1vQTXCNqhh-V5QofRiLER0hF-0EzTTVAFLxNfWuYxUCGexSC2-lqhrGHqEQjAin97jtPGf-1-6asFaUv/pub?embedded=true" },
    { id: 104, name: "Protected Route in React", url: "https://docs.google.com/document/d/e/2PACX-1vSihGBRL8j26ur6JvjkAE9AtWIuekcjO49ij6vFJWjg3k7BdbLmhuLAJyvrDpDvyceNAjHYZ0zTVlJg/pub?embedded=true" },
    { id: 105, name: "Lazy Loading in Router", url: "https://docs.google.com/document/d/e/2PACX-1vQUdlsaMoCzR6Pdk6or4RM97pl0rTnm_IOR8XBhKh2gFukpAeKWQuKDhKb9F0LkacqUm74mrOHp2QlN/pub?embedded=true" },
    { id: 106, name: "React Context (useContext)", url: "https://docs.google.com/document/d/e/2PACX-1vT04urpOHTM8skG0liYoEtvI4fAdd6a0sp9hVBtA8p45s2koytkStNz59AZPsabKt_OZf3wdDYO7Y51/pub?embedded=true" },
    { id: 107, name: "Global State Management", url: "https://docs.google.com/document/d/e/2PACX-1vTAGpNgM1brl5B6zAtNiNb9CR_WCJDkUBpH3ONehwvxfeYS7rUt65tvqSIh12B6vsPT8gRtMvO76znq/pub?embedded=true" },
    { id: 108, name: "Redux", url: "https://docs.google.com/document/d/e/2PACX-1vSrAGQh7CBhcZCng_8juMq4YkxI8TKtT_djTn_hrnB7Sbrpo3EYE11L5yMoSEWLJP6WwxPD983DrORs/pub?embedded=true" },
    { id: 109, name: "React Hooks", url: "https://docs.google.com/document/d/e/2PACX-1vT8_e_pPtauetC2VT15CG9ZNwFKOwsXiyqJ45RUR8IM64OQiqMwuD9E1yZalftw-joBDJVt2C63abIo/pub?embedded=true" },
    { id: 110, name: "useRef", url: "https://docs.google.com/document/d/e/2PACX-1vT1qoJGuBIbHZxC-O0TGJjZimBGNj0u1wvuVm5se-gDicso00DxM-UeCLEDW72_y6lkwpA1gJjOsojN/pub?embedded=true" },
    { id: 111, name: "useReducer Hook", url: "https://docs.google.com/document/d/e/2PACX-1vQdNS4cxQHTIteKArejFfYZAEt0p_8FfjmdWf2eB9Ewfk4qKN15qbyj5BCDFP9tO-zLXOfzM-jWjWKs/pub?embedded=true" },
    { id: 112, name: "useMemo", url: "https://docs.google.com/document/d/e/2PACX-1vSThDWjF5F35rEiBx83qabovk7FtHGBsGlRhGpQbBLNsdphwxXLi96SwC3aF40ALoMyOSl1A_cPBHG1/pub?embedded=true" },
    { id: 113, name: "useCallback", url: "https://docs.google.com/document/d/e/2PACX-1vRKJEf4SXMOGbE2hmShXkxyvWWjmWiQnYprh_xm5Ah9OapLN8fr4rfSC7p5DEuSLjnuuHXyIT_zgMUQ/pub?embedded=true" },
    { id: 114, name: "Axios", url: "https://docs.google.com/document/d/e/2PACX-1vS_K0A8nbHHLnF8xjIbhbkib_vRqx6FcuiSGBvNj5Z28RN3zBUidec6bo2wqzt18tTDckqEA9W34kaY/pub?embedded=true" },
    { id: 115, name: "Axios Interceptor", url: "https://docs.google.com/document/d/e/2PACX-1vQA4KSCBvGPYFz-nnGYMuZCSzUSwtangKPEzDL-ZIC6_bS-i28XME0Tjyb7L6Nqofu_0NP2uLj__byH/pub?embedded=true" },
    { id: 116, name: "Props Drilling", url: "https://docs.google.com/document/d/e/2PACX-1vRfCUH7sACxWJNk_yNw0C8pAGjXO9Ri8YdwPOdQ6AQ5uwwqSesnUGk3nDeWF6Wjtb-QYHmOH6Swndpd/pub?embedded=true" },
 ];

 const pythonCourseData = [
  { id: 1, name: "Python Welcome Page", url: "https://docs.google.com/document/d/e/2PACX-1vRPv6W9HrZ_wPr4G0eW_QfvZm2rQkzO51XP0KSxKuuexkvVWVFw9IziW5ePRHWFvZI8Qsix4G5kOtaY/pub?embedded=true" },
  { id: 2, name: "Python Introduction", url: "https://docs.google.com/document/d/e/2PACX-1vSn7YNU0zVsM5BCFjSnTU_xW9Zv64gv4DY6bWUWGkk5j8LYDAgNJAA5gmUwkqFAhSWi0M8u-BmwcIml/pub?embedded=true" },

  { id: 3, name: "Chapter : 1 Tasks", url: "https://docs.google.com/document/d/e/2PACX-1vR0cfSB6Sa6Nzkcm6jqcpa2g5dtTZxYEuPbe-aW4C453eMLtdrn2Smz4IRjXL7_JFHxEry01vpb8MRR/pub?embedded=true" },

  { id: 4, name: "Variables, Data Types & Operators", url: "https://docs.google.com/document/d/e/2PACX-1vSoKs5w-Gf5L6Qw9hjn5O1Btn8QVK2RsbddU7B7KdSa7gW8OkEu7iUKXN4-3gSPnKP0v8Q6ChwTIpEp/pub?embedded=true" },

  { id: 5, name: "Chapter : 2 Tasks", url: "https://docs.google.com/document/d/e/2PACX-1vTNFGiwDSH7FsnS2SIsbjQkmRiW9mGse5IzUYS-fXSQ6IWBm5mFRwfuHgDRipFuyGRtcY9fSkJvLPv1/pub?embedded=true" },

  { id: 6, name: "Decision Making And Loop Statement", url: "https://docs.google.com/document/d/e/2PACX-1vSRQINZSUUjNrgxgaaf3rG30DpCECcKwDvbFp7UPJqHKKK-_ySHnwI0fdqdzdNHCz6sRw4EUV-FVJH7/pub?embedded=true" },
  
  { id: 7, name: "Chapter : 3 Tasks", url: "https://docs.google.com/document/d/e/2PACX-1vTxclNdITSmz9e3tjNgHe2bFZLaEsaOAx1ttfsF2hTnzLeTCHH2Qp-cDHvZXyzERX0HLGugb-OVnPVN/pub?embedded=true" },

  // { id: 8, name: "CASTING (Type Conversion)", url: "https://docs.google.com/document/d/e/2PACX-1vR3SZq_d9VWFgsQFwnxBmqqULSdqSYL9ozNZlfUJRRYX5EpvZ7HgrbT30Xc87BGdfCCIBKjWqGttsAZ/pub?embedded=true" },

  // { id: 9, name: "PYTHON OPERATORS", url: "https://docs.google.com/document/d/e/2PACX-1vRPXT7S3nxIeiA9NUK8YRaJWaammTwPO1zsGguW4BIi7hJbSAU4sDQ1Sbx3UsjgC-8uClBHWsd-l408/pub?embedded=true" },

  // { id: 10, name: "Python Conditional Statements (Decision Making)", url: "https://docs.google.com/document/d/e/2PACX-1vQYGtsQQD-ipyCL3yV1Ix-Objk2rFkUUn-BXxKEcjepEV92L03B4QnBkUjZCnKILzlFf2NKQzJUzaMl/pub?embedded=true" },
];

export const courseData = {
  React: reactCourseData,
  Python: pythonCourseData
};